### ISSUE TITLE
Can't set a boolean value

### ISSUE THREAD

**Issue by iwarshak** [brenthargrave/motion-config-vars#1]
My app.yml has:

```
AUDIENCE_ENV:
  developer:
    show_logs: Yes
  adhoc:
    show_logs: Yes
  release:
    show_logs: No
```

This fails with:

```
(main)> 2013-05-01 14:38:23.925 TrackGo[85634:c07]  13:in `set:': can't convert true into String (TypeError)
```
